version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "0.0.0.0:27017:27017"  # Expose MongoDB on all interfaces
    volumes:
      - ./data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb

  rust-sentiment-analysis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rust-sentiment-analysis
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    links:
      - mongodb

networks:
  default:
